### ISSUE TITLE
[ERR] domain.com: Something error

### ISSUE THREAD

**Issue by brinhosa** [pwnesia/dnstake#1]
Hello,

I've just installed and tried to run but I'm receiving this error:
Enter a domain to analyze:domain.com

  ·▄▄▄▄   ▐ ▄ .▄▄ ·▄▄▄▄▄ ▄▄▄· ▄ •▄ ▄▄▄ .
  ██▪ ██ •█▌▐█▐█ ▀.•██  ▐█ ▀█ █▌▄▌▪▀▄.▀·
  ▐█· ▐█▌▐█▐▐▌▄▀▀▀█▄▐█.▪▄█▀▀█ ▐▀▀▄·▐▀▀▪▄
  ██. ██ ██▐█▌▐█▄▪▐█▐█▌·▐█ ▪▐▌▐█.█▌▐█▄▄▌
  ▀▀▀▀▀• ▀▀ █▪ ▀▀▀▀ ▀▀▀  ▀  ▀ ·▀  ▀ ▀▀▀

        (c) pwnesia.org — v0.0.1

[ERR] domain.com: Something error

**Comment by reedcrif** [comment]
Had the same issue.

Tested on MacOS 11.5.2 and Kali 2021.2

**Comment by dwisiswant0** [comment]
Can you guys send the details to my Discord (`dw1#0001`) or [DM me on Twitter](https://twitter.com/dwisiswant0)?

**Comment by reedcrif** [comment]
Just sent you a strace from a Kali on Twitter

**Comment by dwisiswant0** [comment]
I confirm that this is not a problem with DNSTake. See [new release](https://github.com/pwnesia/dnstake/releases/tag/v0.0.2).
